### ISSUE TITLE
window.WebviewSdk.close is not a function

### ISSUE THREAD

**Issue by shmuelgutman** [zendesk/sunshine-conversations-webview-date-picker#2]
Trying to use webview-sdk in smooch web chat inside webview.
smooch-web- sdk version: 4.3.0
when calling `window.WebviewSdk.close()` I get the error `window.WebviewSdk.close is not a function`.
Inspecting `window.WebviewSdk` in chrome console I can see that  `window.WebviewSdk` is equal to the dom element `<script id="WebviewSdk" src="https://cdn.smooch.io/webview-sdk.min.js"></script>`
Am I doing anything wrong?

**Comment by lemieux** [comment]
Hey @shmuelgutman, did you put your code inside a function and set it on `window.webviewSdkInit`? This function is called whenever the SDK is properly initialized. 

We identified a problem where the script node shouldn't have `WebviewSdk` as its id since it conflicts with the global variable that is being set once the SDK is loaded. We'll fix that, but in the meantime, it should still work if you put your code inside `window.webviewSdkInit()`. If you look at this example here https://github.com/smooch/webview-date-picker/blob/master/src/components/DatePicker.js#L41 we assign `window.webviewSdkInit` with the action we want to take and once the sdk loads, it will do it.

**Comment by shmuelgutman** [comment]
Yes I did put the code inside `window.webviewSdkInit` and the init is indeed executed but still no luck with the `close` function.
For the seek of simplicity I tried very simple scenario:
```
<html>
<head>
</head>
<script id="WebviewSdk" src="https://cdn.smooch.io/webview-sdk.min.js"></script><script>
    (function(d, s, id) {
        var js,
            fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) {
            return;
        }
        js = d.createElement(s);
        js.id = id;
        js.src = 'https://cdn.smooch.io/webview-sdk.min.js';
        fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'WebviewSdk'));

    window.webviewSdkInit = function() {
        window.WebviewSdk.close()
    }
</script>
<body>
</body></html>
```

In this simple example, I would expect the page to load and immediately close right? I got the same error.

**Comment by lemieux** [comment]
You are right, but I suspect the bug I mentionned above (of having the script id as the same as the global var) is playing trick here. I made the correction in our docs for that, but here's what you could try: 
- Put the webview script loader in the head section of your page, and have your logic in a separate script tag in the body
- Change the id from `WebviewSdk` to `WebviewSdkScript`

I'm thinking that since script has the same id as the global variable that is assigned later when the lib loads and that your `webviewSdkInit` code is in the same scope as the script loader, `window.WebviewSdk` retains a reference to the script tag instead of using the new variable.

**Comment by shmuelgutman** [comment]
I tried your suggestions and no luck.
In your second suggestion, after init, `WebviewSdk` global var is not set on the window obj so `window.WebviewSdk` is `undefined` (obviously `window.WebviewSdk.close()` wont work)
I think that the fact where the script has the same id as the global var it's just the symptom, the actual bug is (probably) laid in the SDK.
My suggestion: pass `WebviewSdk` obj through the `webviewSdkInit` callback (by `this` or by argument) so I can do something like:
```
window.webviewSdkInit = function(sdk) {
        sdk.close(); // or this.close()
    }
```

And another suggestion: open up a repo for this SDK so people can contribute :)

**Comment by lemieux** [comment]
@shmuelgutman the new version is out, this should be fixed. Make sure to clear your cache if the problems still exist
